const data = [  //[世紀, 金賞, 銀賞1, 銀賞2, 銅賞1, 銅賞2, 銅賞3]
    ["Lith A1", 'Akstiletto Prime Blueprint', 'Vectis Prime Blueprint', 'Saryn Prime Neuroptics Blueprint', 'Vasto Prime Receiver', 'Forma Blueprint', 'Braton Prime Barrel'],
    ["Lith A3", 'Akstiletto Prime Blueprint', 'Cernos Prime Blueprint', 'Akbronco Prime Link', 'Valkyr Prime Blueprint', 'Forma Blueprint', 'Lex Prime Barrel'],
    ["Lith A4", 'Akjagara Prime Barrel', 'Tiberon Prime Blueprint', 'Akbolto Prime Barrel', 'Rubico Prime Receiver', 'Orthos Prime Handle', 'Lex Prime Blueprint'],
    ["Lith A2", 'Astilla Prime Barrel', 'Ivara Prime Systems Blueprint', 'Baza Prime Barrel', 'Corinth Prime Blueprint', 'Burston Prime Receiver', 'Forma Blueprint'],
    ["Lith B1", 'Boar Prime Stock', 'Boltor Prime Receiver', 'Rhino Prime Neuroptics Blueprint', 'Forma Blueprint', 'Ankyros Prime Blueprint', 'Mag Prime Neuroptics Blueprint'],
    ["Lith B2", 'Ballistica Prime Blueprint', 'Orthos Prime Blade', 'Braton Prime Receiver', 'Tigris Prime Stock', 'Paris Prime Lower Limb', 'Forma Blueprint'],
    ["Lith B3", 'Ballistica Prime Blueprint', 'Orthos Prime Blade', 'Cernos Prime String', 'Limbo Prime Systems Blueprint', 'Forma Blueprint', 'Burston Prime Blueprint'],
    ["Lith B4", 'Boltor Prime Blueprint', 'Scindo Prime Blueprint', 'Rhino Prime Neuroptics Blueprint', 'Nyx Prime Blueprint', 'Forma Blueprint', 'Ankyros Prime Blueprint'],
    ["Lith B5", 'Ballistica Prime Blueprint', 'Orthos Prime Blade', 'Rubico Prime Stock', 'Banshee Prime Neuroptics Blueprint', 'Lex Prime Receiver', 'Oberon Prime Chassis Blueprint'],
    ["Lith B6", 'Ballistica Prime Blueprint', 'Redeemer Prime Blueprint', 'Orthos Prime Blueprint', 'Limbo Prime Systems Blueprint', 'Lex Prime Barrel', 'Fang Prime Blueprint'],
    ["Lith B7", 'Baza Prime Blueprint', 'Orthos Prime Blueprint', 'Aksomati Prime Barrel', 'Tipedo Prime Blueprint', 'Lex Prime Receiver', 'Forma Blueprint'],
    ["Lith B8", 'Baza Prime Blueprint', 'Ivara Prime Blueprint', 'Atlas Prime Chassis Blueprint', 'Dethcube Prime Systems', 'Burston Prime Stock', 'Aksomati Prime Blueprint'],
    ["Lith C1", 'Carrier Prime Cerebrum', 'Forma Blueprint', 'Kavasa Prime Band', 'Nova Prime Systems Blueprint', 'Nova Prime Neuroptics Blueprint', 'Fang Prime Blade'],
    ["Lith C2", 'Cernos Prime Lower Limb', 'Nami Skyla Prime Handle', 'Akbolto Prime Barrel', 'Venka Prime Blades', 'Paris Prime Upper Limb', 'Bronco Prime Receiver'],
    ["Lith C3", 'Chroma Prime Neuroptics Blueprint', 'Braton Prime Blueprint', 'Helios Prime Blueprint', 'Lex Prime Blueprint', 'Silva & Aegis Prime Hilt', 'Sybaris Prime Blueprint'],
    ["Lith C4", 'Chroma Prime Neuroptics Blueprint', 'Orthos Prime Blade', 'Braton Prime Stock', 'Paris Prime Lower Limb', 'Forma Blueprint', 'Burston Prime Receiver'],
    ["Lith C5", 'Cernos Prime Lower Limb', 'Venka Prime Blueprint', 'Valkyr Prime Neuroptics Blueprint', 'Spira Prime Blueprint', 'Saryn Prime Neuroptics Blueprint', 'Forma Blueprint'],
    ["Lith C6", 'Corinth Prime Stock', 'Mesa Prime Blueprint', 'Braton Prime Receiver', 'Forma Blueprint', 'Fang Prime Blade', 'Equinox Prime Chassis Blueprint'],
    ["Lith C8", 'Chroma Prime Neuroptics Blueprint', 'Rubico Prime Stock', 'Forma Blueprint', 'Zephyr Prime Neuroptics Blueprint', 'Tiberon Prime Blueprint', 'Burston Prime Receiver'],
    ["Lith D1", 'Dethcube Prime Blueprint', 'Ninkondi Prime Chain', 'Mesa Prime Blueprint', 'Lex Prime Receiver', 'Burston Prime Receiver', 'Atlas Prime Blueprint'],
    ["Lith D2", 'Dethcube Prime Cerebrum', 'Redeemer Prime Blueprint', 'Fang Prime Handle', 'Wukong Prime Neuroptics Blueprint', 'Forma Blueprint', 'Equinox Prime Chassis Blueprint'],
    ["Lith D3", 'Dethcube Prime Blueprint', 'Ninkondi Prime Chain', 'Corinth Prime Receiver', 'Stradavar Prime Receiver', 'Ivara Prime Neuroptics Blueprint', 'Burston Prime Stock'],
    ["Lith D4", 'Dethcube Prime Blueprint', 'Zakti Prime Barrel', 'Ninkondi Prime Chain', 'Orthos Prime Handle', 'Forma Blueprint', 'Bronco Prime Blueprint'],
    ["Lith F1", 'Fragor Prime Blueprint', 'Odonata Prime Blueprint', 'Scindo Prime Blueprint', 'Fang Prime Blade', 'Paris Prime Blueprint', 'Forma Blueprint'],
    ["Lith F2", 'Vauban Prime Blueprint', 'Fang Prime Handle', 'Burston Prime Barrel', 'Paris Prime Upper Limb', 'Hikou Prime Stars', 'Odonata Prime Systems Blueprint'],
    ["Lith G1", 'Glaive Prime Blueprint', 'Forma Blueprint', 'Ember Prime Systems Blueprint', 'Reaper Prime Handle', 'Frost Prime Chassis Blueprint', 'Latron Prime Blueprint'],
    ["Lith G2", 'Glaive Prime Blueprint', 'Loki Prime Chassis Blueprint', 'Frost Prime Systems Blueprint', 'Wyrm Prime Cerebrum', 'Latron Prime Stock', 'Bo Prime Blueprint'],
    ["Lith G3", 'Guandao Prime Handle', 'Panthera Prime Stock', 'Forma Blueprint', 'Zhuge Prime String', 'Paris Prime Upper Limb', 'Octavia Prime Neuroptics Blueprint'],
    ["Lith H1", 'Helios Prime Cerebrum', 'Nami Skyla Prime Handle', 'Akstiletto Prime Barrel', 'Saryn Prime Systems Blueprint', 'Paris Prime Blueprint', 'Bronco Prime Blueprint'],
    ["Lith H2", 'Helios Prime Cerebrum', 'Oberon Prime Blueprint', 'Orthos Prime Blueprint', 'Lex Prime Barrel', 'Forma Blueprint', 'Zephyr Prime Neuroptics Blueprint'],
    ["Lith I1", 'Ivara Prime Chassis Blueprint', 'Karyst Prime Handle', 'Burston Prime Barrel', 'Pandero Prime Blueprint', 'Forma Blueprint', 'Fang Prime Blade'],
    ["Lith K1", 'Kavasa Prime Buckle', 'Trinity Prime Blueprint', 'Tigris Prime Barrel', 'Odonata Prime Harness Blueprint', 'Burston Prime Stock', 'Fang Prime Blueprint'],
    ["Lith K2", 'Kogake Prime Gauntlet', 'Forma Blueprint', 'Braton Prime Receiver', 'Zephyr Prime Neuroptics Blueprint', 'Rubico Prime Receiver', 'Braton Prime Barrel'],
    ["Lith K3", 'Kronen Prime Blade', 'Wukong Prime Chassis Blueprint', 'Tiberon Prime Blueprint', 'Rubico Prime Receiver', 'Paris Prime Upper Limb', 'Forma Blueprint'],
    ["Lith K4", 'Kavasa Prime Buckle', 'Trinity Prime Blueprint', 'Soma Prime Receiver', 'Nova Prime Neuroptics Blueprint', 'Forma Blueprint', 'Dual Kamas Prime Blueprint'],
    ["Lith K6", 'Karyst Prime Blade', 'Paris Prime Grip', 'Gara Prime Chassis Blueprint', 'Bronco Prime Blueprint', 'Atlas Prime Blueprint', 'Aksomati Prime Receiver'],
    ["Lith K7", 'Karyst Prime Blade', 'Octavia Prime Chassis Blueprint', 'Forma Blueprint', 'Paris Prime Lower Limb', 'Guandao Prime Blade', 'Baza Prime Receiver'],
    ["Lith K8", 'Kavasa Prime Buckle', 'Limbo Prime Neuroptics Blueprint', 'Trinity Prime Neuroptics Blueprint', 'Forma Blueprint', 'Braton Prime Receiver', 'Lex Prime Receiver'],
    ["Lith L1", 'Limbo Prime Neuroptics Blueprint', 'Zhuge Prime Blueprint', 'Equinox Prime Neuroptics Blueprint', 'Kogake Prime Boot', 'Forma Blueprint', 'Destreza Prime Handle'],
    ["Lith L2", 'Limbo Prime Neuroptics Blueprint', 'Tekko Prime Blueprint', 'Braton Prime Receiver', 'Redeemer Prime Blade', 'Pyrana Prime Barrel', 'Equinox Prime Chassis Blueprint'],
    ["Lith L3", 'Limbo Prime Chassis Blueprint', 'Trinity Prime Chassis Blueprint', 'Kavasa Prime Band', 'Dual Kamas Prime Blueprint', 'Pyrana Prime Barrel', 'Lex Prime Barrel'],
    ["Lith M1", 'Mag Prime Blueprint', 'Dakra Prime Blueprint', 'Soma Prime Blueprint', 'Forma Blueprint', 'Boar Prime Receiver', 'Lex Prime Receiver'],
    ["Lith M2", 'Mag Prime Blueprint', 'Forma Blueprint', 'Boar Prime Barrel', 'Soma Prime Barrel', 'Nova Prime Neuroptics Blueprint', 'Dakra Prime Handle'],
    ["Lith M3", 'Mesa Prime Neuroptics Blueprint', 'Rubico Prime Stock', 'Oberon Prime Blueprint', 'Silva & Aegis Prime Hilt', 'Paris Prime Blueprint', 'Forma Blueprint'],
    ["Lith M4", 'Mesa Prime Neuroptics Blueprint', 'Stradavar Prime Barrel', 'Destreza Prime Blueprint', 'Paris Prime Blueprint', 'Equinox Prime Chassis Blueprint', 'Akjagara Prime Blueprint'],
    ["Lith M5", 'Mesa Prime Neuroptics Blueprint', 'Titania Prime Blueprint', 'Stradavar Prime Barrel', 'Redeemer Prime Blade', 'Burston Prime Stock', 'Atlas Prime Blueprint'],
    ["Lith M6", 'Mesa Prime Systems Blueprint', 'Dethcube Prime Carapace', 'Akjagara Prime Receiver', 'Inaros Prime Systems Blueprint', 'Forma Blueprint', 'Bronco Prime Blueprint'],
    ["Lith N1", 'Nova Prime Chassis Blueprint', 'Forma Blueprint', 'Akbronco Prime Link', 'Fang Prime Blade', 'Bronco Prime Blueprint', 'Nekros Prime Chassis Blueprint'],
    ["Lith N2", 'Nekros Prime Systems Blueprint', 'Kavasa Prime Band', 'Helios Prime Blueprint', 'Carrier Prime Systems', 'Spira Prime Blueprint', 'Paris Prime Upper Limb'],
    ["Lith N3", 'Nekros Prime Blueprint', 'Forma Blueprint', 'Braton Prime Blueprint', 'Valkyr Prime Blueprint', 'Burston Prime Receiver', 'Sybaris Prime Stock'],
    ["Lith N4", 'Ninkondi Prime Handle', 'Ivara Prime Blueprint', 'Atlas Prime Systems Blueprint', 'Gram Prime Blade', 'Forma Blueprint', 'Bronco Prime Blueprint'],
    ["Lith N5", 'Ninkondi Prime Handle', 'Ivara Prime Blueprint', 'Braton Prime Receiver', 'Zhuge Prime String', 'Stradavar Prime Stock', 'Forma Blueprint'],
    ["Lith N6", 'Nezha Prime Neuroptics Blueprint', 'Stradavar Prime Barrel', 'Inaros Prime Chassis Blueprint', 'Zhuge Prime Grip', 'Fang Prime Blade', 'Aksomati Prime Receiver'],
    ["Lith N7", 'Nidus Prime Chassis Blueprint', 'Ivara Prime Blueprint', 'Pangolin Prime Blade', 'Braton Prime Blueprint', 'Octavia Prime Systems Blueprint', 'Lex Prime Barrel'],
    ["Lith N8", 'Nezha Prime Neuroptics Blueprint', 'Zakti Prime Barrel', 'Titania Prime Neuroptics Blueprint', 'Pandero Prime Blueprint', 'Astilla Prime Receiver', 'Aksomati Prime Blueprint'],
    ["Lith N9", 'Nami Skyla Prime Blade', 'Mesa Prime Blueprint', 'Akjagara Prime Receiver', 'Burston Prime Stock', 'Redeemer Prime Blade', 'Forma Blueprint'],
    ["Lith O1", 'Oberon Prime Neuroptics Blueprint', 'Akbolto Prime Barrel', 'Forma Blueprint', 'Rubico Prime Receiver', 'Burston Prime Blueprint', 'Ballistica Prime Lower Limb'],
    ["Lith O2", 'Odonata Prime Wings Blueprint', 'Loki Prime Chassis Blueprint', 'Forma Blueprint', 'Wyrm Prime Cerebrum', 'Volt Prime Blueprint', 'Bo Prime Blueprint'],
    ["Lith P1", 'Pyrana Prime Blueprint', 'Forma Blueprint', 'Braton Prime Receiver', 'Sybaris Prime Stock', 'Helios Prime Carapace', 'Fang Prime Blade'],
    ["Lith P2", 'Pyrana Prime Blueprint', 'Gram Prime Blueprint', 'Ballistica Prime Receiver', 'Tipedo Prime Blueprint', 'Forma Blueprint', 'Burston Prime Blueprint'],
    ["Lith P3", 'Panthera Prime Barrel', 'Burston Prime Barrel', 'Akjagara Prime Link', 'Stradavar Prime Stock', 'Forma Blueprint', 'Atlas Prime Blueprint'],
    ["Lith P4", 'Panthera Prime Barrel', 'Forma Blueprint', 'Equinox Prime Blueprint', 'Titania Prime Chassis Blueprint', 'Bronco Prime Blueprint', 'Braton Prime Barrel'],
    ["Lith P5", 'Pangolin Prime Blueprint', 'Tekko Prime Blueprint', 'Guandao Prime Blueprint', 'Lex Prime Blueprint', 'Bronco Prime Receiver', 'Atlas Prime Blueprint'],
    ["Lith R1", 'Redeemer Prime Handle', 'Ballistica Prime Receiver', 'Burston Prime Barrel', 'Hydroid Prime Chassis Blueprint', 'Mesa Prime Chassis Blueprint', 'Forma Blueprint'],
    ["Lith S1", 'Spira Prime Pouch', 'Forma Blueprint', 'Paris Prime Grip', 'Bronco Prime Blueprint', 'Hikou Prime Blueprint', 'Paris Prime String'],
    ["Lith S10", 'Stradavar Prime Blueprint', 'Orthos Prime Blueprint', 'Baza Prime Barrel', 'Mesa Prime Chassis Blueprint', 'Dethcube Prime Systems', 'Burston Prime Blueprint'],
    ["Lith S2", 'Soma Prime Stock', 'Kavasa Prime Band', 'Forma Blueprint', 'Nyx Prime Blueprint', 'Akbronco Prime Blueprint', 'Carrier Prime Systems'],
    ["Lith S3", 'Spira Prime Pouch', 'Soma Prime Receiver', 'Ash Prime Blueprint', 'Paris Prime String', 'Akbronco Prime Blueprint', 'Carrier Prime Systems'],
    ["Lith S4", 'Saryn Prime Blueprint', 'Kavasa Prime Kubrow Collar Blueprint', 'Trinity Prime Chassis Blueprint', 'Paris Prime Blueprint', 'Forma Blueprint', 'Lex Prime Blueprint'],
    ["Lith S5", 'Spira Prime Blade', 'Galatine Prime Handle', 'Akbronco Prime Link', 'Fang Prime Blade', 'Burston Prime Receiver', 'Carrier Prime Carapace'],
    ["Lith S6", 'Spira Prime Pouch', 'Valkyr Prime Neuroptics Blueprint', 'Kavasa Prime Band', 'Dual Kamas Prime Blueprint', 'Fang Prime Blade', 'Forma Blueprint'],
    ["Lith S7", 'Sybaris Prime Barrel', 'Paris Prime Grip', 'Akbolto Prime Link', 'Mirage Prime Chassis Blueprint', 'Lex Prime Blueprint', 'Galatine Prime Blade'],
    ["Lith S8", 'Stradavar Prime Blueprint', 'Rubico Prime Barrel', 'Orthos Prime Blueprint', 'Gram Prime Blade', 'Forma Blueprint', 'Braton Prime Barrel'],
    ["Lith S9", 'Silva & Aegis Prime Guard', 'Tigris Prime Receiver', 'Oberon Prime Blueprint', 'Sybaris Prime Stock', 'Forma Blueprint', 'Burston Prime Stock'],
    ["Lith T1", 'Tigris Prime Blueprint', 'Valkyr Prime Neuroptics Blueprint', 'Ballistica Prime Upper Limb', 'Forma Blueprint', 'Burston Prime Blueprint', 'Akbronco Prime Blueprint'],
    ["Lith T2", 'Tiberon Prime Stock', 'Silva & Aegis Prime Blueprint', 'Braton Prime Blueprint', 'Lex Prime Barrel', 'Valkyr Prime Blueprint', 'Forma Blueprint'],
    ["Lith T3", 'Tigris Prime Blueprint', 'Nekros Prime Blueprint', 'Forma Blueprint', 'Oberon Prime Chassis Blueprint', 'Galatine Prime Blade', 'Braton Prime Stock'],
    ["Lith T4", 'Titania Prime Systems Blueprint', 'Karyst Prime Handle', 'Dethcube Prime Carapace', 'Zakti Prime Receiver', 'Tekko Prime Gauntlet', 'Paris Prime Lower Limb'],
    ["Lith T5", 'Tenora Prime Barrel', 'Zhuge Prime Blueprint', 'Titania Prime Neuroptics Blueprint', 'Paris Prime Lower Limb', 'Forma Blueprint', 'Corinth Prime Blueprint'],
    ["Lith T6", 'Tiberon Prime Stock', 'Kronen Prime Handle', 'Burston Prime Barrel', 'Rubico Prime Barrel', 'Forma Blueprint', 'Braton Prime Blueprint'],
    ["Lith T7", 'Titania Prime Systems Blueprint', 'Strun Prime Barrel', 'Ivara Prime Systems Blueprint', 'Gara Prime Systems Blueprint', 'Bronco Prime Blueprint', 'Forma Blueprint'],
    ["Lith V1", 'Fragor Prime Handle', 'Forma Blueprint', 'Volt Prime Systems Blueprint', 'Burston Prime Stock', 'Paris Prime Lower Limb', 'Paris Prime Upper Limb'],
    ["Lith V2", 'Vauban Prime Systems Blueprint', 'Paris Prime Upper Limb', 'Forma Blueprint', 'Paris Prime Lower Limb', 'Lex Prime Barrel', 'Fang Prime Blueprint'],
    ["Lith V3", 'Valkyr Prime Systems Blueprint', 'Helios Prime Systems', 'Tigris Prime Barrel', 'Braton Prime Blueprint', 'Cernos Prime Upper Limb', 'Paris Prime Lower Limb'],
    ["Lith V4", 'Vauban Prime Chassis Blueprint', 'Helios Prime Blueprint', 'Tigris Prime Barrel', 'Venka Prime Blades', 'Nekros Prime Chassis Blueprint', 'Spira Prime Blueprint'],
    ["Lith V5", 'Valkyr Prime Systems Blueprint', 'Ballistica Prime Upper Limb', 'Akbolto Prime Barrel', 'Lex Prime Blueprint', 'Banshee Prime Neuroptics Blueprint', 'Akbronco Prime Blueprint'],
    ["Lith V6", 'Valkyr Prime Chassis Blueprint', 'Saryn Prime Blueprint', 'Forma Blueprint', 'Venka Prime Blades', 'Nikana Prime Blueprint', 'Cernos Prime Grip'],
    ["Lith V7", 'Vauban Prime Neuroptics Blueprint', 'Ash Prime Blueprint', 'Akstiletto Prime Link', 'Vectis Prime Barrel', 'Fragor Prime Head', 'Carrier Prime Blueprint'],
    ["Lith V8", 'Vauban Prime Systems Blueprint', 'Vectis Prime Stock', 'Fragor Prime Handle', 'Forma Blueprint', 'Bronco Prime Blueprint', 'Ash Prime Chassis Blueprint'],
    ["Lith W1", 'Wukong Prime Blueprint', 'Fang Prime Handle', 'Akbolto Prime Link', 'Mirage Prime Neuroptics Blueprint', 'Gram Prime Blade', 'Forma Blueprint'],
    ["Lith W2", 'Wukong Prime Blueprint', 'Fang Prime Handle', 'Baza Prime Barrel', 'Stradavar Prime Receiver', 'Rubico Prime Receiver', 'Forma Blueprint'],
    ["Lith Z1", 'Zephyr Prime Systems Blueprint', 'Cernos Prime Blueprint', 'Forma Blueprint', 'Mirage Prime Neuroptics Blueprint', 'Akbronco Prime Blueprint', 'Fang Prime Handle'],
    ["Lith Z2", 'Zephyr Prime Systems Blueprint', 'Silva & Aegis Prime Blueprint', 'Helios Prime Systems', 'Nami Skyla Prime Blueprint', 'Forma Blueprint', 'Akbronco Prime Blueprint'],
    // Meso
    ["Meso A1", 'Akjagara Prime Barrel', 'Kronen Prime Handle', 'Forma Blueprint', 'Sybaris Prime Stock', 'Orthos Prime Handle', 'Ballistica Prime Lower Limb'],
    ["Meso A2", 'Akbolto Prime Receiver', 'Zephyr Prime Chassis Blueprint', 'Equinox Prime Blueprint', 'Zhuge Prime Grip', 'Tipedo Prime Blueprint', 'Forma Blueprint'],
    ["Meso B1", 'Boar Prime Stock', 'Orthos Prime Blueprint', 'Mag Prime Chassis Blueprint', 'Forma Blueprint', 'Orthos Prime Handle', 'Dakra Prime Handle'],
    ["Meso B2", 'Banshee Prime Chassis Blueprint', 'Kronen Prime Handle', 'Hydroid Prime Blueprint', 'Silva & Aegis Prime Hilt', 'Oberon Prime Chassis Blueprint', 'Braton Prime Blueprint'],
    ["Meso B3", 'Boar Prime Stock', 'Mag Prime Chassis Blueprint', 'Dakra Prime Blueprint', 'Soma Prime Blueprint', 'Nova Prime Systems Blueprint', 'Forma Blueprint'],
    ["Meso B4", 'Baza Prime Blueprint', 'Wukong Prime Chassis Blueprint', 'Redeemer Prime Blueprint', 'Paris Prime Upper Limb', 'Chroma Prime Blueprint', 'Bronco Prime Receiver'],
    ["Meso B5", 'Baza Prime Blueprint', 'Guandao Prime Blueprint', 'Volnus Prime Head', 'Ivara Prime Neuroptics Blueprint', 'Nidus Prime Systems Blueprint', 'Karyst Prime Blueprint'],
    ["Meso B6", 'Baza Prime Stock', 'Paris Prime Grip', 'Forma Blueprint', 'Akbronco Prime Blueprint', 'Magnus Prime Blueprint', 'Octavia Prime Neuroptics Blueprint'],
    ["Meso B7", 'Ballistica Prime Blueprint', 'Akjagara Prime Link', 'Redeemer Prime Blueprint', 'Fang Prime Blueprint', 'Burston Prime Receiver', 'Forma Blueprint'],
    ["Meso C1", 'Carrier Prime Cerebrum', 'Ash Prime Blueprint', 'Scindo Prime Handle', 'Saryn Prime Systems Blueprint', 'Forma Blueprint', 'Nova Prime Neuroptics Blueprint'],
    ["Meso C2", 'Carrier Prime Cerebrum', 'Odonata Prime Blueprint', 'Valkyr Prime Neuroptics Blueprint', 'Galatine Prime Blade', 'Bronco Prime Blueprint', 'Cernos Prime Upper Limb'],
    ["Meso C3", 'Cernos Prime Lower Limb', 'Saryn Prime Blueprint', 'Helios Prime Blueprint', 'Nami Skyla Prime Blueprint', 'Lex Prime Blueprint', 'Burston Prime Stock'],
    ["Meso C4", 'Chroma Prime Systems Blueprint', 'Forma Blueprint', 'Atlas Prime Systems Blueprint', 'Mesa Prime Chassis Blueprint', 'Ivara Prime Neuroptics Blueprint', 'Braton Prime Stock'],
    ["Meso C5", 'Corinth Prime Barrel', 'Forma Blueprint', 'Chroma Prime Chassis Blueprint', 'Tipedo Prime Blueprint', 'Stradavar Prime Stock', 'Burston Prime Blueprint'],
    ["Meso C6", 'Corinth Prime Stock', 'Nezha Prime Blueprint', 'Forma Blueprint', 'Lex Prime Barrel', 'Burston Prime Blueprint', 'Baza Prime Receiver'],
    // ["Meso D1", 'Dual Kamas Prime Blade', 'Orthos Prime Blade', 'Forma Blueprint', 'Forma Blueprint', 'Lex Prime Blueprint', 'Orthos Prime Handle'],
    ["Meso D2", 'Destreza Prime Blade', 'Valkyr Prime Neuroptics Blueprint', 'Helios Prime Systems', 'Paris Prime Lower Limb', 'Lex Prime Receiver', 'Forma Blueprint'],
    ["Meso D3", 'Destreza Prime Blade', 'Nami Skyla Prime Handle', 'Kronen Prime Handle', 'Fang Prime Handle', 'Braton Prime Stock', 'Akbolto Prime Blueprint'],
    ["Meso D4", 'Dual Kamas Prime Blade', 'Vasto Prime Blueprint', 'Nova Prime Blueprint', 'Trinity Prime Neuroptics Blueprint', 'Soma Prime Barrel', 'Forma Blueprint'],
    ["Meso D5", 'Dethcube Prime Cerebrum', 'Nezha Prime Blueprint', 'Aksomati Prime Barrel', 'Paris Prime Blueprint', 'Octavia Prime Systems Blueprint', 'Ivara Prime Neuroptics Blueprint'],
    ["Meso D6", 'Ember Prime Blueprint', 'Wyrm Prime Systems', 'Forma Blueprint', 'Latron Prime Barrel', 'Frost Prime Chassis Blueprint', 'Bo Prime Ornament'],
    ["Meso E1", 'Equinox Prime Systems Blueprint', 'Rubico Prime Stock', 'Akbolto Prime Link', 'Pyrana Prime Barrel', 'Destreza Prime Handle', 'Bronco Prime Blueprint'],
    ["Meso E2", 'Equinox Prime Systems Blueprint', 'Stradavar Prime Barrel', 'Atlas Prime Chassis Blueprint', 'Forma Blueprint', 'Destreza Prime Handle', 'Bronco Prime Receiver'],
    ["Meso E3", 'Equinox Prime Systems Blueprint', 'Titania Prime Neuroptics Blueprint', 'Tekko Prime Blueprint', 'Paris Prime Blueprint', 'Forma Blueprint', 'Baza Prime Receiver'],
    ["Meso E4", 'Fragor Prime Blueprint', 'Dual Kamas Prime Handle', 'Nekros Prime Neuroptics Blueprint', 'Saryn Prime Systems Blueprint', 'Paris Prime Lower Limb', 'Bronco Prime Receiver'],
    ["Meso F1", 'Frost Prime Blueprint', 'Forma Blueprint', 'Reaper Prime Blade', 'Sicarus Prime Barrel', 'Ember Prime Chassis Blueprint', 'Latron Prime Stock'],
    ["Meso F2", 'Frost Prime Blueprint', 'Glaive Prime Disc', 'Forma Blueprint', 'Reaper Prime Handle', 'Loki Prime Blueprint', 'Ember Prime Neuroptics Blueprint'],
    ["Meso F3", 'Galatine Prime Blueprint', 'Silva & Aegis Prime Blade', 'Ballistica Prime String', 'Venka Prime Blades', 'Forma Blueprint', 'Braton Prime Barrel'],
    ["Meso G1", 'Guandao Prime Handle', 'Burston Prime Barrel', 'Atlas Prime Systems Blueprint', 'Orthos Prime Handle', 'Forma Blueprint', 'Equinox Prime Chassis Blueprint'],
    ["Meso G2", 'Helios Prime Cerebrum', 'Oberon Prime Blueprint', 'Fragor Prime Blueprint', 'Paris Prime Blueprint', 'Mirage Prime Neuroptics Blueprint', 'Hydroid Prime Chassis Blueprint'],
    ["Meso H1", 'Inaros Prime Neuroptics Blueprint', 'Orthos Prime Blade', 'Atlas Prime Systems Blueprint', 'Titania Prime Chassis Blueprint', 'Paris Prime Upper Limb', 'Corinth Prime Blueprint'],
    ["Meso I1", 'Kogake Prime Gauntlet', 'Tigris Prime Receiver', 'Akstiletto Prime Barrel', 'Orthos Prime Handle', 'Nekros Prime Chassis Blueprint', 'Cernos Prime Upper Limb'],
    ["Meso K1", 'Kronen Prime Blade', 'Wukong Prime Systems Blueprint', 'Chroma Prime Chassis Blueprint', 'Paris Prime String', 'Orthos Prime Handle', 'Mirage Prime Chassis Blueprint'],
    ["Meso K2", 'Karyst Prime Blade', 'Wukong Prime Chassis Blueprint', 'Forma Blueprint', 'Orthos Prime Handle', 'Ninkondi Prime Blueprint', 'Braton Prime Stock'],
    ["Meso K3", 'Limbo Prime Chassis Blueprint', 'Dethcube Prime Carapace', 'Chroma Prime Chassis Blueprint', 'Tipedo Prime Blueprint', 'Ninkondi Prime Blueprint', 'Burston Prime Receiver'],
    ["Meso L1", 'Mag Prime Blueprint', 'Rhino Prime Chassis Blueprint', 'Boar Prime Barrel', 'Ankyros Prime Gauntlet', 'Boltor Prime Barrel', 'Dakra Prime Handle'],
    ["Meso M1", 'Mirage Prime Blueprint', 'Silva & Aegis Prime Blade', 'Akjagara Prime Link', 'Paris Prime String', 'Kogake Prime Boot', 'Fang Prime Blade'],
    ["Meso M2", 'Mirage Prime Blueprint', 'Kogake Prime Blueprint', 'Equinox Prime Neuroptics Blueprint', 'Paris Prime String', 'Gram Prime Blade', 'Ballistica Prime Lower Limb'],
    ["Meso M3", 'Nyx Prime Neuroptics Blueprint', 'Dual Kamas Prime Handle', 'Forma Blueprint', 'Fang Prime Blueprint', 'Braton Prime Stock', 'Fang Prime Handle'],
    ["Meso N1", 'Ninkondi Prime Handle', 'Panthera Prime Stock', 'Bronco Prime Barrel', 'Tipedo Prime Blueprint', 'Pangolin Prime Handle', 'Ivara Prime Neuroptics Blueprint'],
    ["Meso N10", 'Vauban Prime Neuroptics Blueprint', 'Forma Blueprint', 'Ash Prime Neuroptics Blueprint', 'Fang Prime Handle', 'Bronco Prime Blueprint', 'Hikou Prime Blueprint'],
    ["Meso N2", 'Nekros Prime Blueprint', 'Carrier Prime Cerebrum', 'Euphona Prime Barrel', 'Braton Prime Barrel', 'Bronco Prime Blueprint', 'Burston Prime Stock'],
    ["Meso N3", 'Nikana Prime Blade', 'Oberon Prime Blueprint', 'Forma Blueprint', 'Orthos Prime Handle', 'Saryn Prime Systems Blueprint', 'Paris Prime Upper Limb'],
    ["Meso N4", 'Nekros Prime Systems Blueprint', 'Tigris Prime Receiver', 'Hydroid Prime Blueprint', 'Lex Prime Receiver', 'Forma Blueprint', 'Braton Prime Stock'],
    ["Meso N5", 'Nyx Prime Neuroptics Blueprint', 'Scindo Prime Handle', 'Rhino Prime Chassis Blueprint', 'Hikou Prime Pouch', 'Forma Blueprint', 'Boltor Prime Barrel'],
    ["Meso N6", 'Ninkondi Prime Handle', 'Gram Prime Blueprint', 'Forma Blueprint', 'Pyrana Prime Barrel', 'Limbo Prime Systems Blueprint', 'Kronen Prime Blueprint'],
    ["Meso N7", 'Ninkondi Prime Handle', 'Gram Prime Blueprint', 'Forma Blueprint', 'Pyrana Prime Barrel', 'Limbo Prime Systems Blueprint', 'Kronen Prime Blueprint'],
    ["Meso N8", 'Nikana Prime Hilt', 'Valkyr Prime Neuroptics Blueprint', 'Cernos Prime String', 'Valkyr Prime Blueprint', 'Forma Blueprint', 'Cernos Prime Upper Limb'],
    ["Meso N9", 'Ninkondi Prime Handle', 'Ivara Prime Blueprint', 'Akjagara Prime Link', 'Tekko Prime Gauntlet', 'Paris Prime String', 'Forma Blueprint'],
    ["Meso O1", 'Oberon Prime Neuroptics Blueprint', 'Cernos Prime String', 'Akstiletto Prime Link', 'Paris Prime Lower Limb', 'Akbronco Prime Blueprint', 'Forma Blueprint'],
    ["Meso O2", 'Oberon Prime Neuroptics Blueprint', 'Akbronco Prime Link', 'Mirage Prime Systems Blueprint', 'Cernos Prime Upper Limb', 'Paris Prime Lower Limb', 'Tiberon Prime Receiver'],
    ["Meso O3", 'Odonata Prime Wings Blueprint', 'Wyrm Prime Systems', 'Volt Prime Chassis Blueprint', 'Odonata Prime Systems Blueprint', 'Loki Prime Neuroptics Blueprint', 'Forma Blueprint'],
    ["Meso O4", 'Oberon Prime Neuroptics Blueprint', 'Nekros Prime Neuroptics Blueprint', 'Galatine Prime Handle', 'Silva & Aegis Prime Hilt', 'Forma Blueprint', 'Fang Prime Blueprint'],
    ["Meso P1", 'Pyrana Prime Blueprint', 'Silva & Aegis Prime Blueprint', 'Ballistica Prime Receiver', 'Oberon Prime Chassis Blueprint', 'Chroma Prime Blueprint', 'Bronco Prime Receiver'],
    ["Meso P2", 'Panthera Prime Receiver', 'Zhuge Prime Blueprint', 'Ivara Prime Systems Blueprint', 'Forma Blueprint', 'Braton Prime Receiver', 'Baza Prime Receiver'],
    ["Meso P3", 'Pangolin Prime Blueprint', 'Mesa Prime Blueprint', 'Forma Blueprint', 'Zhuge Prime Grip', 'Lex Prime Blueprint', 'Karyst Prime Blueprint'],
    ["Meso P6", 'Pyrana Prime Blueprint', 'Kavasa Prime Kubrow Collar Blueprint', 'Trinity Prime Blueprint', 'Braton Prime Blueprint', 'Destreza Prime Handle', 'Forma Blueprint'],
    ["Meso R1", 'Rubico Prime Blueprint', 'Akbronco Prime Link', 'Ballistica Prime String', 'Tiberon Prime Receiver', 'Paris Prime Upper Limb', 'Braton Prime Blueprint'],
    ["Meso R2", 'Rubico Prime Blueprint', 'Mesa Prime Blueprint', 'Destreza Prime Blueprint', 'Forma Blueprint', 'Fang Prime Blueprint', 'Aksomati Prime Blueprint'],
    ["Meso R3", 'Rubico Prime Blueprint', 'Dethcube Prime Carapace', 'Bronco Prime Barrel', 'Zhuge Prime Grip', 'Pangolin Prime Handle', 'Akjagara Prime Blueprint'],
    ["Meso R4", 'Rubico Prime Blueprint', 'Forma Blueprint', 'Chroma Prime Systems Blueprint', 'Zephyr Prime Chassis Blueprint', 'Gram Prime Blade', 'Braton Prime Barrel'],
    ["Meso S1", 'Soma Prime Stock', 'Odonata Prime Blueprint', 'Paris Prime Upper Limb', 'Tigris Prime Stock', 'Paris Prime Blueprint', 'Nova Prime Systems Blueprint'],
    ["Meso S10", 'Strun Prime Blueprint', 'Aksomati Prime Barrel', 'Titania Prime Blueprint', 'Paris Prime String', 'Corinth Prime Blueprint', 'Forma Blueprint'],
    ["Meso S2", 'Saryn Prime Chassis Blueprint', 'Forma Blueprint', 'Paris Prime Grip', 'Galatine Prime Blade', 'Bronco Prime Blueprint', 'Paris Prime String'],
    ["Meso S3", 'Spira Prime Pouch', 'Forma Blueprint', 'Ash Prime Blueprint', 'Akbronco Prime Blueprint', 'Nekros Prime Chassis Blueprint', 'Valkyr Prime Blueprint'],
    ["Meso S4", 'Saryn Prime Blueprint', 'Trinity Prime Blueprint', 'Fang Prime Handle', 'Galatine Prime Blade', 'Banshee Prime Neuroptics Blueprint', 'Fang Prime Blueprint'],
    ["Meso S5", 'Sybaris Prime Barrel', 'Saryn Prime Neuroptics Blueprint', 'Forma Blueprint', 'Lex Prime Barrel', 'Braton Prime Barrel', 'Burston Prime Stock'],
    ["Meso S6", 'Spira Prime Blade', 'Tigris Prime Receiver', 'Cernos Prime String', 'Valkyr Prime Blueprint', 'Helios Prime Carapace', 'Galatine Prime Blade'],
    ["Meso S7", 'Sybaris Prime Barrel', 'Paris Prime Grip', 'Nami Skyla Prime Handle', 'Venka Prime Blades', 'Forma Blueprint', 'Cernos Prime Upper Limb'],
    ["Meso S8", 'Sybaris Prime Barrel', 'Ballistica Prime Upper Limb', 'Burston Prime Barrel', 'Gram Prime Blade', 'Forma Blueprint', 'Bronco Prime Receiver'],
    ["Meso S9", 'Spira Prime Pouch', 'Saryn Prime Neuroptics Blueprint', 'Forma Blueprint', 'Braton Prime Blueprint', 'Spira Prime Blueprint', 'Lex Prime Barrel'],
    ["Meso T1", 'Tiberon Prime Barrel', 'Forma Blueprint', 'Paris Prime Upper Limb', 'Burston Prime Receiver', 'Braton Prime Stock', 'Fang Prime Blueprint'],
    ["Meso T2", 'Tiberon Prime Stock', 'Banshee Prime Blueprint', 'Tigris Prime Receiver', 'Forma Blueprint', 'Paris Prime Lower Limb', 'Lex Prime Barrel'],
    ["Meso T3", 'Tiberon Prime Stock', 'Chroma Prime Chassis Blueprint', 'Limbo Prime Blueprint', 'Lex Prime Barrel', 'Forma Blueprint', 'Paris Prime Lower Limb'],
    ["Meso T4", 'Tenora Prime Receiver', 'Wukong Prime Systems Blueprint', 'Paris Prime Grip', 'Zhuge Prime Grip', 'Ninkondi Prime Blueprint', 'Forma Blueprint'],
    ["Meso T5", 'Tenora Prime Barrel', 'Panthera Prime Stock', 'Astilla Prime Stock', 'Paris Prime Upper Limb', 'Tekko Prime Gauntlet', 'Forma Blueprint'],
    ["Meso V1", 'Vectis Prime Receiver', 'Forma Blueprint', 'Braton Prime Blueprint', 'Carrier Prime Blueprint', 'Spira Prime Blueprint', 'Burston Prime Blueprint'],
    ["Meso V2", 'Nikana Prime Blade', 'Volt Prime Chassis Blueprint', 'Forma Blueprint', 'Ash Prime Chassis Blueprint', 'Paris Prime Blueprint', 'Vasto Prime Receiver'],
    ["Meso V3", 'Valkyr Prime Systems Blueprint', 'Volt Prime Chassis Blueprint', 'Kavasa Prime Band', 'Spira Prime Blueprint', 'Forma Blueprint', 'Carrier Prime Blueprint'],
    ["Meso V4", 'Vauban Prime Chassis Blueprint', 'Ash Prime Neuroptics Blueprint', 'Valkyr Prime Neuroptics Blueprint', 'Forma Blueprint', 'Lex Prime Barrel', 'Carrier Prime Blueprint'],
    ["Meso V5", 'Venka Prime Gauntlet', 'Silva & Aegis Prime Blueprint', 'Euphona Prime Barrel', 'Spira Prime Blueprint', 'Cernos Prime Grip', 'Bronco Prime Blueprint'],
    ["Meso V6", 'Vectis Prime Receiver', 'Vauban Prime Blueprint', 'Carrier Prime Cerebrum', 'Forma Blueprint', 'Braton Prime Barrel', 'Akstiletto Prime Barrel'],
    ["Meso W1", 'Wukong Prime Blueprint', 'Zephyr Prime Chassis Blueprint', 'Fang Prime Handle', 'Zhuge Prime String', 'Tipedo Prime Blueprint', 'Tekko Prime Gauntlet'],
    ["Meso Z1", 'Zephyr Prime Blueprint', 'Limbo Prime Blueprint', 'Helios Prime Blueprint', 'Forma Blueprint', 'Fang Prime Blueprint', 'Burston Prime Receiver'],
    ["Meso Z2", 'Zephyr Prime Systems Blueprint', 'Rubico Prime Barrel', 'Hydroid Prime Blueprint', 'Sybaris Prime Blueprint', 'Redeemer Prime Blade', 'Braton Prime Blueprint'],
    ["Meso Z3", 'Zephyr Prime Systems Blueprint', 'Rubico Prime Barrel', 'Akjagara Prime Link', 'Stradavar Prime Receiver', 'Forma Blueprint', 'Chroma Prime Blueprint'],
    //Neo
    ['NeoA1', 'Akstiletto Prime Blueprint', 'Vectis Prime Blueprint', 'Cernos Prime String', 'Forma Blueprint', 'Braton Prime Barrel', 'Carrier Prime Systems'],
    ['NeoA2', 'Akbolto Prime Receiver', 'Zephyr Prime Chassis Blueprint', 'Forma Blueprint', 'Pyrana Prime Barrel', 'Limbo Prime Systems Blueprint', 'Kronen Prime Blueprint'],
    ['NeoA3', 'Akjagara Prime Barrel', 'Equinox Prime Neuroptics Blueprint', 'Atlas Prime Systems Blueprint', 'Zhuge Prime Grip', 'Mesa Prime Chassis Blueprint', 'Lex Prime Barrel'],
    ['NeoA4', 'Akstiletto Prime Blueprint', 'Vectis Prime Blueprint', 'Ash Prime Neuroptics Blueprint', 'Vauban Prime Chassis Blueprint', 'Forma Blueprint', 'Carrier Prime Carapace'],
    ['NeoA5', 'Atlas Prime Neuroptics Blueprint', 'Octavia Prime Chassis Blueprint', 'Karyst Prime Handle', 'Paris Prime String', 'Gara Prime Systems Blueprint', 'Forma Blueprint'],
    ['NeoA6', 'Akjagara Prime Barrel', 'Hydroid Prime Blueprint', 'Ballistica Prime String', 'Burston Prime Blueprint', 'Nami Skyla Prime Blueprint', 'Forma Blueprint'],
    ['NeoB1', 'Banshee Prime Chassis Blueprint', 'Burston Prime Barrel', 'Vectis Prime Stock', 'Bronco Prime Receiver', 'Trinity Prime Systems Blueprint', 'Paris Prime String'],
    ['NeoB2', 'Banshee Prime Chassis Blueprint', 'Forma Blueprint', 'Venka Prime Blueprint', 'Fang Prime Blueprint', 'Braton Prime Stock', 'Tigris Prime Stock'],
    ['NeoB3', 'Boltor Prime Blueprint', 'Dakra Prime Blade', 'Mag Prime Chassis Blueprint', 'Rhino Prime Systems Blueprint', 'Forma Blueprint', 'Boar Prime Blueprint'],
    ['NeoB4', 'Banshee Prime Systems Blueprint', 'Tigris Prime Barrel', 'Kronen Prime Handle', 'Forma Blueprint', 'Burston Prime Stock', 'Hydroid Prime Chassis Blueprint'],
    ['NeoB5', 'Banshee Prime Systems Blueprint', 'Oberon Prime Blueprint', 'Destreza Prime Blueprint', 'Forma Blueprint', 'Braton Prime Barrel', 'Ballistica Prime Lower Limb'],
    ['NeoB7', 'Baza Prime Stock', 'Tekko Prime Blueprint', 'Dethcube Prime Carapace', 'Tenora Prime Blueprint', 'Braton Prime Blueprint', 'Aksomati Prime Receiver'],
    ['NeoC1', 'Chroma Prime Systems Blueprint', 'Redeemer Prime Blueprint', 'Pyrana Prime Receiver', 'Mesa Prime Chassis Blueprint', 'Limbo Prime Systems Blueprint', 'Kronen Prime Blueprint'],
    ['NeoD1', 'Dakra Prime Blade', 'Forma Blueprint', 'Trinity Prime Neuroptics Blueprint', 'Boar Prime Blueprint', 'Vasto Prime Barrel', 'Mag Prime Systems Blueprint'],
    ['NeoD2', 'Dethcube Prime Cerebrum', 'Titania Prime Blueprint', 'Equinox Prime Neuroptics Blueprint', 'Nezha Prime Systems Blueprint', 'Forma Blueprint', 'Braton Prime Stock'],
    ['NeoD3', 'Dethcube Prime Blueprint', 'Zakti Prime Barrel', 'Forma Blueprint', 'Nezha Prime Systems Blueprint', 'Akbronco Prime Blueprint', 'Paris Prime Lower Limb'],
    ['NeoD4', 'Destreza Prime Blade', 'Dual Kamas Prime Handle', 'Limbo Prime Blueprint', 'Braton Prime Barrel', 'Trinity Prime Systems Blueprint', 'Forma Blueprint'],
    ['NeoE1', 'Ember Prime Blueprint', 'Reaper Prime Blade', 'Forma Blueprint', 'Wyrm Prime Blueprint', 'Loki Prime Neuroptics Blueprint', 'Frost Prime Neuroptics Blueprint'],
    ['NeoE2', 'Equinox Prime Systems Blueprint', 'Zakti Prime Barrel', 'Atlas Prime Chassis Blueprint', 'Dethcube Prime Systems', 'Corinth Prime Blueprint', 'Burston Prime Receiver'],
    ['NeoF1', 'Frost Prime Blueprint', 'Forma Blueprint', 'Bo Prime Handle', 'Sicarus Prime Blueprint', 'Sicarus Prime Barrel', 'Ember Prime Chassis Blueprint'],
    ['NeoG1', 'Gram Prime Handle', 'Paris Prime Grip', 'Hydroid Prime Neuroptics Blueprint', 'Mirage Prime Neuroptics Blueprint', 'Forma Blueprint', 'Kogake Prime Boot'],
    ['NeoG2', 'Gram Prime Handle', 'Zhuge Prime Blueprint', 'Pyrana Prime Receiver', 'Redeemer Prime Blade', 'Forma Blueprint', 'Dethcube Prime Systems'],
    ['NeoG3', 'Galatine Prime Blueprint', 'Sybaris Prime Receiver', 'Silva & Aegis Prime Blueprint', 'Forma Blueprint', 'Fang Prime Blade', 'Burston Prime Receiver'],
    ['NeoH1', 'Hydroid Prime Systems Blueprint', 'Tigris Prime Barrel', 'Banshee Prime Blueprint', 'Orthos Prime Handle', 'Fragor Prime Head', 'Burston Prime Receiver'],
    ['NeoH2', 'Hydroid Prime Systems Blueprint', 'Rubico Prime Barrel', 'Ballistica Prime Receiver', 'Euphona Prime Blueprint', 'Burston Prime Stock', 'Fang Prime Blueprint'],
    ['NeoH3', 'Hydroid Prime Systems Blueprint', 'Nami Skyla Prime Handle', 'Mesa Prime Systems Blueprint', 'Forma Blueprint', 'Fang Prime Handle', 'Ballistica Prime Lower Limb'],
    ['NeoI1', 'Ivara Prime Chassis Blueprint', 'Limbo Prime Blueprint', 'Akjagara Prime Receiver', 'Zhuge Prime String', 'Wukong Prime Neuroptics Blueprint', 'Fang Prime Blade'],
    ['NeoI2', 'Ivara Prime Chassis Blueprint', 'Wukong Prime Systems Blueprint', 'Stradavar Prime Barrel', 'Forma Blueprint', 'Dethcube Prime Systems', 'Burston Prime Receiver'],
    ['NeoK1', 'Kogake Prime Gauntlet', 'Zephyr Prime Chassis Blueprint', 'Helios Prime Blueprint', 'Valkyr Prime Blueprint', 'Silva & Aegis Prime Hilt', 'Euphona Prime Blueprint'],
    ['NeoK2', 'Kogake Prime Gauntlet', 'Mirage Prime Systems Blueprint', 'Akbolto Prime Link', 'Chroma Prime Blueprint', 'Braton Prime Barrel', 'Banshee Prime Neuroptics Blueprint'],
    ['NeoK3', 'Kronen Prime Blade', 'Tiberon Prime Barrel', 'Braton Prime Receiver', 'Rubico Prime Receiver', 'Forma Blueprint', 'Burston Prime Blueprint'],
    ['NeoL1', 'Limbo Prime Chassis Blueprint', 'Silva & Aegis Prime Blade', 'Ballistica Prime Receiver', 'Mirage Prime Chassis Blueprint', 'Kronen Prime Blueprint', 'Euphona Prime Blueprint'],
    ['NeoM1', 'Mirage Prime Blueprint', 'Helios Prime Blueprint', 'Euphona Prime Barrel', 'Paris Prime String', 'Bronco Prime Blueprint', 'Akbolto Prime Blueprint'],
    ['NeoM2', 'Mesa Prime Systems Blueprint', 'Limbo Prime Blueprint', 'Bronco Prime Barrel', 'Forma Blueprint', 'Burston Prime Stock', 'Akbronco Prime Blueprint'],
    ['NeoM3', 'Mesa Prime Systems Blueprint', 'Forma Blueprint', 'Atlas Prime Chassis Blueprint', 'Titania Prime Chassis Blueprint', 'Ivara Prime Neuroptics Blueprint', 'Bronco Prime Receiver'],
    ['NeoN1', 'Nyx Prime Chassis Blueprint', 'Kavasa Prime Kubrow Collar Blueprint', 'Soma Prime Receiver', 'Forma Blueprint', 'Vectis Prime Barrel', 'Hikou Prime Stars'],
    ['Neo N10', 'Nami Skyla Prime Blade', 'Tipedo Prime Ornament', 'Ballistica Prime Upper Limb', 'Zephyr Prime Neuroptics Blueprint', 'Redeemer Prime Blade', 'Forma Blueprint'],
    ['NeoN11', 'Nekros Prime Systems Blueprint', 'Oberon Prime Systems Blueprint', 'Forma Blueprint', 'Tigris Prime Stock', 'Sybaris Prime Blueprint', 'Braton Prime Barrel'],
    ['NeoN12', 'Nova Prime Chassis Blueprint', 'Kavasa Prime Band', 'Dual Kamas Prime Handle', 'Vasto Prime Receiver', 'Trinity Prime Systems Blueprint', 'Soma Prime Blueprint'],
    ['NeoN13', 'Nezha Prime Chassis Blueprint', 'Wukong Prime Chassis Blueprint', 'Forma Blueprint', 'Pangolin Prime Handle', 'Inaros Prime Systems Blueprint', 'Aksomati Prime Blueprint'],
    ['NeoN14', 'Ninkondi Prime Handle', 'Zhuge Prime Receiver', 'Braton Prime Receiver', 'Titania Prime Chassis Blueprint', 'Forma Blueprint', 'Bronco Prime Receiver'],
    ['NeoN15', 'Nezha Prime Neuroptics Blueprint', 'Baza Prime Barrel', 'Atlas Prime Systems Blueprint', 'Paris Prime Blueprint', 'Forma Blueprint', 'Akbronco Prime Blueprint'],
    ['NeoN2', 'Vauban Prime Systems Blueprint', 'Nova Prime Blueprint', 'Forma Blueprint', 'Vasto Prime Barrel', 'Fang Prime Blueprint', 'Lex Prime Blueprint'],
    ['NeoN3', 'Nekros Prime Systems Blueprint', 'Ash Prime Neuroptics Blueprint', 'Fang Prime Handle', 'Paris Prime String', 'Odonata Prime Systems Blueprint', 'Lex Prime Barrel'],
    ['NeoN4', 'Nikana Prime Blade', 'Venka Prime Blueprint', 'Forma Blueprint', 'Braton Prime Stock', 'Ash Prime Chassis Blueprint', 'Paris Prime String'],
    ['NeoN5', 'Nikana Prime Blueprint', 'Akstiletto Prime Link', 'Ash Prime Systems Blueprint', 'Helios Prime Carapace', 'Forma Blueprint', 'Saryn Prime Systems Blueprint'],
    ['NeoN6', 'Nikana Prime Hilt', 'Trinity Prime Blueprint', 'Sybaris Prime Receiver', 'Cernos Prime Upper Limb', 'Galatine Prime Blade', 'Bronco Prime Receiver'],
    ['NeoN7', 'Nekros Prime Systems Blueprint', 'Valkyr Prime Neuroptics Blueprint', 'Banshee Prime Blueprint', 'Venka Prime Blades', 'Euphona Prime Blueprint', 'Trinity Prime Neuroptics Blueprint'],
    ['NeoN8', 'Nami Skyla Prime Blade', 'Forma Blueprint', 'Akbolto Prime Link', 'Sybaris Prime Blueprint', 'Paris Prime String', 'Hydroid Prime Chassis Blueprint'],
    ['NeoN9', 'Nova Prime Chassis Blueprint', 'Soma Prime Receiver', 'Forma Blueprint', 'Mag Prime Neuroptics Blueprint', 'Dakra Prime Handle', 'Boar Prime Blueprint'],
    ['NeoP1', 'Pangolin Prime Blueprint', 'Rubico Prime Stock', 'Akjagara Prime Receiver', 'Redeemer Prime Blade', 'Paris Prime Lower Limb', 'Ninkondi Prime Blueprint'],
    ['NeoP2', 'Pandero Prime Receiver', 'Titania Prime Blueprint', 'Forma Blueprint', 'Guandao Prime Blade', 'Braton Prime Stock', 'Aksomati Prime Receiver'],
    ['NeoR1', 'Rhino Prime Blueprint', 'Nyx Prime Chassis Blueprint', 'Boltor Prime Receiver', 'Hikou Prime Blueprint', 'Forma Blueprint', 'Ankyros Prime Gauntlet'],
    ['NeoR2', 'Rubico Prime Blueprint', 'Tiberon Prime Blueprint', 'Paris Prime Grip', 'Ninkondi Prime Blueprint', 'Forma Blueprint', 'Braton Prime Stock'],
    ['NeoR3', 'Redeemer Prime Handle', 'Paris Prime Grip', 'Ninkondi Prime Chain', 'Limbo Prime Systems Blueprint', 'Burston Prime Blueprint', 'Baza Prime Receiver'],
    ['NeoR4', 'Redeemer Prime Handle', 'Ninkondi Prime Chain', 'Corinth Prime Receiver', 'Mesa Prime Chassis Blueprint', 'Braton Prime Stock', 'Aksomati Prime Blueprint'],
    ['NeoS1', 'Saryn Prime Blueprint', 'Forma Blueprint', 'Trinity Prime Chassis Blueprint', 'Soma Prime Blueprint', 'Lex Prime Barrel', 'Carrier Prime Carapace'],
    ['NeoS10', 'Saryn Prime Chassis Blueprint', 'Nikana Prime Blade', 'Spira Prime Blade', 'Braton Prime Stock', 'Saryn Prime Systems Blueprint', 'Lex Prime Blueprint'],
    ['NeoS11', 'Stradavar Prime Blueprint', 'Kronen Prime Handle', 'Forma Blueprint', 'Hydroid Prime Chassis Blueprint', 'Fang Prime Blade', 'Bronco Prime Receiver'],
    ['NeoS12', 'Stradavar Prime Blueprint', 'Wukong Prime Chassis Blueprint', 'Mirage Prime Systems Blueprint', 'Redeemer Prime Blade', 'Paris Prime Upper Limb', 'Fang Prime Blade'],
    ['NeoS13', 'Saryn Prime Chassis Blueprint', 'Forma Blueprint', 'Cernos Prime Blueprint', 'Spira Prime Blueprint', 'Saryn Prime Systems Blueprint', 'Nikana Prime Blueprint'],
    ['NeoS14', 'Stradavar Prime Blueprint', 'Pangolin Prime Blade', 'Fang Prime Handle', 'Ninkondi Prime Blueprint', 'Karyst Prime Blueprint', 'Forma Blueprint'],
    ['NeoS2', 'Saryn Prime Chassis Blueprint', 'Paris Prime Upper Limb', 'Nyx Prime Systems Blueprint', 'Nova Prime Systems Blueprint', 'Paris Prime Lower Limb', 'Burston Prime Stock'],
    ['NeoS3', 'Spira Prime Blade', 'Vasto Prime Blueprint', 'Forma Blueprint', 'Burston Prime Receiver', 'Carrier Prime Blueprint', 'Soma Prime Barrel'],
    ['NeoS5', 'Sicarus Prime Receiver', 'Frost Prime Systems Blueprint', 'Glaive Prime Disc', 'Reaper Prime Blueprint', 'Ember Prime Neuroptics Blueprint', 'Latron Prime Receiver'],
    ['NeoS6', 'Silva & Aegis Prime Guard', 'Kavasa Prime Buckle', 'Tigris Prime Receiver', 'Trinity Prime Neuroptics Blueprint', 'Forma Blueprint', 'Burston Prime Blueprint'],
    ['NeoS7', 'Silva & Aegis Prime Guard', 'Sybaris Prime Receiver', 'Ballistica Prime Receiver', 'Helios Prime Carapace', 'Fang Prime Blade', 'Banshee Prime Neuroptics Blueprint'],
    ['NeoS8', 'Spira Prime Pouch', 'Nikana Prime Blueprint', 'Fragor Prime Blueprint', 'Hydroid Prime Chassis Blueprint', 'Forma Blueprint', 'Bronco Prime Receiver'],
    ['NeoS9', 'Silva & Aegis Prime Guard', 'Forma Blueprint', 'Destreza Prime Blueprint', 'Mirage Prime Neuroptics Blueprint', 'Bronco Prime Blueprint', 'Akjagara Prime Blueprint'],
    ['NeoT1', 'Tigris Prime Blueprint', 'Fragor Prime Handle', 'Banshee Prime Blueprint', 'Burston Prime Blueprint', 'Dual Kamas Prime Blueprint', 'Forma Blueprint'],
    ['NeoT2', 'Tekko Prime Blade', 'Forma Blueprint', 'Dethcube Prime Carapace', 'Wukong Prime Neuroptics Blueprint', 'Fang Prime Blueprint', 'Akbronco Prime Blueprint'],
    ['NeoT3', 'Titania Prime Systems Blueprint', 'Inaros Prime Chassis Blueprint', 'Atlas Prime Chassis Blueprint', 'Redeemer Prime Blade', 'Forma Blueprint', 'Braton Prime Blueprint'],
    ['NeoT4', 'Tenora Prime Receiver', 'Astilla Prime Blueprint', 'Guandao Prime Blueprint', 'Braton Prime Stock', 'Ivara Prime Neuroptics Blueprint', 'Forma Blueprint'],
    ['NeoT5', 'Tenora Prime Barrel', 'Magnus Prime Receiver', 'Corinth Prime Receiver', 'Inaros Prime Systems Blueprint', 'Aksomati Prime Receiver', 'Braton Prime Barrel'],
    ['NeoV1', 'Nova Prime Chassis Blueprint', 'Volt Prime Blueprint', 'Bronco Prime Barrel', 'Dual Kamas Prime Blueprint', 'Forma Blueprint', 'Nyx Prime Blueprint'],
    ['NeoV2', 'Vauban Prime Blueprint', 'Forma Blueprint', 'Galatine Prime Handle', 'Galatine Prime Blade', 'Braton Prime Stock', 'Fang Prime Handle'],
    ['NeoV3', 'Vauban Prime Neuroptics Blueprint', 'Forma Blueprint', 'Tigris Prime Receiver', 'Carrier Prime Systems', 'Paris Prime String', 'Galatine Prime Blade'],
    ['NeoV4', 'Venka Prime Gauntlet', 'Ash Prime Neuroptics Blueprint', 'Saryn Prime Neuroptics Blueprint', 'Bronco Prime Receiver', 'Tigris Prime Stock', 'Cernos Prime Grip'],
    ['NeoV5', 'Vauban Prime Neuroptics Blueprint', 'Burston Prime Barrel', 'Forma Blueprint', 'Silva & Aegis Prime Hilt', 'Paris Prime String', 'Helios Prime Carapace'],
    ['NeoV6', 'Vauban Prime Chassis Blueprint', 'Mirage Prime Systems Blueprint', 'Fragor Prime Handle', 'Forma Blueprint', 'Cernos Prime Grip', 'Burston Prime Stock'],
    ['NeoV7', 'Valkyr Prime Chassis Blueprint', 'Cernos Prime Blueprint', 'Banshee Prime Blueprint', 'Pyrana Prime Barrel', 'Forma Blueprint', 'Akbolto Prime Blueprint'],
    ['NeoV8', 'Volt Prime Neuroptics Blueprint', 'Forma Blueprint', 'Bo Prime Handle', 'Wyrm Prime Blueprint', 'Odonata Prime Harness Blueprint', 'Loki Prime Blueprint'],
    ['NeoZ1', 'Zephyr Prime Blueprint', 'Galatine Prime Handle', 'Forma Blueprint', 'Paris Prime Blueprint', 'Nekros Prime Chassis Blueprint', 'Orthos Prime Handle'],
    ['NeoZ2', 'Zephyr Prime Blueprint', 'Pyrana Prime Receiver', 'Mesa Prime Blueprint', 'Lex Prime Blueprint', 'Braton Prime Stock', 'Akbolto Prime Blueprint'],
    ['NeoZ3', 'Zhuge Prime Barrel', 'Mesa Prime Blueprint', 'Akjagara Prime Receiver', 'Zephyr Prime Neuroptics Blueprint', 'Forma Blueprint', 'Bronco Prime Receiver'],
    ['NeoZ4', 'Zephyr Prime Blueprint', 'Redeemer Prime Blueprint', 'Forma Blueprint', 'Paris Prime String', 'Kronen Prime Blueprint', 'Burston Prime Stock'],
    ['NeoZ5', 'Zhuge Prime Barrel', 'Forma Blueprint', 'Aksomati Prime Barrel', 'Lex Prime Barrel', 'Burston Prime Stock', 'Akjagara Prime Blueprint'],
    ['NeoZ6', 'Zhuge Prime Barrel', 'Titania Prime Neuroptics Blueprint', 'Tipedo Prime Ornament', 'Paris Prime String', 'Guandao Prime Blade', 'Braton Prime Blueprint'],
    ['NeoZ7', 'Zhuge Prime Barrel', 'Octavia Prime Chassis Blueprint', 'Akbronco Prime Link', 'Wukong Prime Neuroptics Blueprint', 'Forma Blueprint', 'Atlas Prime Blueprint'],
    ['NeoZ8', 'Zephyr Prime Systems Blueprint', 'Gram Prime Blueprint', 'Forma Blueprint', 'Kronen Prime Blueprint', 'Chroma Prime Chassis Blueprint', 'Braton Prime Stock'],
    //Axi
    ['Axi A1', 'Nikana Prime Blueprint', 'Dual Kamas Prime Handle', 'Akstiletto Prime Barrel', 'Braton Prime Stock', 'Fragor Prime Head', 'Trinity Prime Systems Blueprint'],
    ['Axi A10', 'Aksomati Prime Link', 'Wukong Prime Chassis Blueprint', 'Paris Prime Grip', 'Stradavar Prime Receiver', 'Forma Blueprint', 'Akbronco Prime Blueprint'],
    ['Axi A11', 'Atlas Prime Neuroptics Blueprint', 'Wukong Prime Systems Blueprint', 'Pangolin Prime Blade', 'Zhuge Prime String', 'Fang Prime Blueprint', 'Burston Prime Receiver'],
    ['Axi A13', 'Aksomati Prime Link', 'Pangolin Prime Blade', 'Orthos Prime Blueprint', 'Inaros Prime Systems Blueprint', 'Forma Blueprint', 'Burston Prime Receiver'],
    ['Axi A14', 'Aksomati Prime Link', 'Karyst Prime Handle', 'Nidus Prime Blueprint', 'Paris Prime Blueprint', 'Zakti Prime Receiver', 'Volnus Prime Blueprint'],
    ['Axi A3', 'Akbolto Prime Receiver', 'Hydroid Prime Neuroptics Blueprint', 'Cernos Prime String', 'Kogake Prime Boot', 'Helios Prime Carapace', 'Braton Prime Barrel'],
    ['Axi A4', 'Akbolto Prime Receiver', 'Fang Prime Handle', 'Ballistica Prime String', 'Zephyr Prime Neuroptics Blueprint', 'Forma Blueprint', 'Braton Prime Stock'],
    ['Axi A6', 'Atlas Prime Neuroptics Blueprint', 'Zhuge Prime Blueprint', 'Tipedo Prime Ornament', 'Orthos Prime Handle', 'Chroma Prime Blueprint', 'Braton Prime Stock'],
    ['Axi A7', 'Ash Prime Systems Blueprint', 'Fragor Prime Blueprint', 'Forma Blueprint', 'Carrier Prime Systems', 'Braton Prime Blueprint', 'Akstiletto Prime Receiver'],
    ['Axi A8', 'Aksomati Prime Link', 'Gram Prime Blueprint', 'Forma Blueprint', 'Pyrana Prime Barrel', 'Equinox Prime Chassis Blueprint', 'Braton Prime Stock'],
    ['Axi A9', 'Atlas Prime Neuroptics Blueprint', 'Ivara Prime Systems Blueprint', 'Akbronco Prime Link', 'Rubico Prime Stock', 'Lex Prime Blueprint', 'Gram Prime Blade'],
    ['Axi B1', 'Banshee Prime Systems Blueprint', 'Kavasa Prime Buckle', 'Cernos Prime Blueprint', 'Fang Prime Blade', 'Ash Prime Chassis Blueprint', 'Euphona Prime Blueprint'],
    ['Axi B2', 'Banshee Prime Systems Blueprint', 'Orthos Prime Blueprint', 'Forma Blueprint', 'Fang Prime Blade', 'Sybaris Prime Blueprint', 'Fragor Prime Head'],
    ['Axi B3', 'Baza Prime Stock', 'Zhuge Prime Receiver', 'Atlas Prime Chassis Blueprint', 'Stradavar Prime Stock', 'Paris Prime Lower Limb', 'Forma Blueprint'],
    ['Axi B4', 'Baza Prime Blueprint', 'Karyst Prime Handle', 'Ivara Prime Blueprint', 'Paris Prime Lower Limb', 'Aksomati Prime Blueprint', 'Akjagara Prime Blueprint'],
    ['Axi C1', 'Cernos Prime Lower Limb', 'Forma Blueprint', 'Orthos Prime Blueprint', 'Lex Prime Receiver', 'Vectis Prime Barrel', 'Trinity Prime Neuroptics Blueprint'],
    ['Axi C2', 'Cernos Prime Lower Limb', 'Fragor Prime Handle', 'Silva & Aegis Prime Blade', 'Braton Prime Blueprint', 'Trinity Prime Systems Blueprint', 'Forma Blueprint'],
    ['Axi C3', 'Chroma Prime Systems Blueprint', 'Banshee Prime Blueprint', 'Pyrana Prime Receiver', 'Helios Prime Carapace', 'Forma Blueprint', 'Hydroid Prime Chassis Blueprint'],
    ['Axi C4', 'Chroma Prime Systems Blueprint', 'Sybaris Prime Receiver', 'Kogake Prime Blueprint', 'Pyrana Prime Barrel', 'Hydroid Prime Chassis Blueprint', 'Braton Prime Blueprint'],
    ['Axi C5', 'Corinth Prime Barrel', 'Tipedo Prime Ornament', 'Akbronco Prime Link', 'Tekko Prime Gauntlet', 'Panthera Prime Blueprint', 'Braton Prime Barrel'],
    ['Axi C6', 'Corinth Prime Barrel', 'Pandero Prime Barrel', 'Ivara Prime Systems Blueprint', 'Pangolin Prime Handle', 'Karyst Prime Blueprint', 'Forma Blueprint'],
    ['Axi D1', 'Destreza Prime Blade', 'Zhuge Prime Receiver', 'Forma Blueprint', 'Tiberon Prime Receiver', 'Chroma Prime Blueprint', 'Braton Prime Blueprint'],
    ['Axi D2', 'Destreza Prime Blade', 'Rubico Prime Stock', 'Forma Blueprint', 'Destreza Prime Handle', 'Braton Prime Blueprint', 'Aksomati Prime Receiver'],
    ['Axi D3', 'Dual Kamas Prime Blade', 'Pyrana Prime Receiver', 'Destreza Prime Blueprint', 'Lex Prime Blueprint', 'Limbo Prime Systems Blueprint', 'Braton Prime Stock'],
    ['Axi E1', 'Ember Prime Blueprint', 'Forma Blueprint', 'Glaive Prime Blade', 'Frost Prime Neuroptics Blueprint', 'Sicarus Prime Blueprint', 'Latron Prime Barrel'],
    ['Axi E2', 'Euphona Prime Receiver', 'Forma Blueprint', 'Bronco Prime Barrel', 'Braton Prime Stock', 'Lex Prime Receiver', 'Paris Prime Blueprint'],
    ['Axi G1', 'Galatine Prime Blueprint', 'Forma Blueprint', 'Kavasa Prime Kubrow Collar Blueprint', 'Paris Prime Blueprint', 'Saryn Prime Systems Blueprint', 'Nekros Prime Chassis Blueprint'],
    ['Axi G2', 'Gram Prime Handle', 'Tipedo Prime Ornament', 'Redeemer Prime Blueprint', 'Wukong Prime Neuroptics Blueprint', 'Burston Prime Receiver', 'Akbolto Prime Blueprint'],
    ['Axi G3', 'Gram Prime Handle', 'Kronen Prime Handle', 'Burston Prime Barrel', 'Ninkondi Prime Blueprint', 'Lex Prime Blueprint', 'Forma Blueprint'],
    ['Axi G4', 'Gram Prime Handle', 'Pangolin Prime Blade', 'Burston Prime Barrel', 'Tekko Prime Gauntlet', 'Fang Prime Blueprint', 'Aksomati Prime Receiver'],
    ['Axi G5', 'Gram Prime Handle', 'Zephyr Prime Blueprint', 'Forma Blueprint', 'Tiberon Prime Receiver', 'Chroma Prime Blueprint', 'Burston Prime Stock'],
    ['Axi G6', 'Gara Prime Blueprint', 'Nezha Prime Blueprint', 'Braton Prime Stock', 'Karyst Prime Blueprint', 'Forma Blueprint', 'Aksomati Prime Blueprint'],
    ['Axi H1', 'Helios Prime Cerebrum', 'Trinity Prime Chassis Blueprint', 'Akstiletto Prime Receiver', 'Vectis Prime Barrel', 'Fragor Prime Head', 'Forma Blueprint'],
    ['Axi H2', 'Helios Prime Cerebrum', 'Akstiletto Prime Barrel', 'Trinity Prime Chassis Blueprint', 'Fang Prime Handle', 'Lex Prime Receiver', 'Oberon Prime Chassis Blueprint'],
    ['Axi H3', 'Hydroid Prime Systems Blueprint', 'Forma Blueprint', 'Burston Prime Barrel', 'Helios Prime Carapace', 'Cernos Prime Grip', 'Kronen Prime Blueprint'],
    ['Axi H4', 'Hydroid Prime Systems Blueprint', 'Forma Blueprint', 'Akbolto Prime Link', 'Paris Prime Upper Limb', 'Mirage Prime Chassis Blueprint', 'Mesa Prime Chassis Blueprint'],
    ['Axi I1', 'Inaros Prime Neuroptics Blueprint', 'Volnus Prime Head', 'Forma Blueprint', 'Pangolin Prime Handle', 'Panthera Prime Blueprint', 'Dethcube Prime Systems'],
    ['Axi I2', 'Inaros Prime Neuroptics Blueprint', 'Gara Prime Chassis Blueprint', 'Baza Prime Barrel', 'Tenora Prime Blueprint', 'Strun Prime Receiver', 'Forma Blueprint'],
    ['Axi K1', 'Kavasa Prime Buckle', 'Akstiletto Prime Receiver', 'Forma Blueprint', 'Lex Prime Barrel', 'Hikou Prime Pouch', 'Odonata Prime Harness Blueprint'],
    ['Axi K2', 'Kronen Prime Blade', 'Galatine Prime Handle', 'Cernos Prime String', 'Forma Blueprint', 'Sybaris Prime Blueprint', 'Orthos Prime Handle'],
    ['Axi K3', 'Kronen Prime Blade', 'Pyrana Prime Receiver', 'Banshee Prime Blueprint', 'Tiberon Prime Receiver', 'Paris Prime Blueprint', 'Cernos Prime Grip'],
    ['Axi K4', 'Kronen Prime Blade', 'Kogake Prime Blueprint', 'Destreza Prime Blueprint', 'Sybaris Prime Stock', 'Paris Prime Blueprint', 'Forma Blueprint'],
    ['Axi K5', 'Kronen Prime Blade', 'Hydroid Prime Blueprint', 'Equinox Prime Blueprint', 'Forma Blueprint', 'Braton Prime Blueprint', 'Ballistica Prime Lower Limb'],
    ['Axi L1', 'Loki Prime Systems Blueprint', 'Glaive Prime Blade', 'Forma Blueprint', 'Wyrm Prime Carapace', 'Reaper Prime Blueprint', 'Latron Prime Blueprint'],
    ['Axi L2', 'Limbo Prime Neuroptics Blueprint', 'Tiberon Prime Blueprint', 'Forma Blueprint', 'Orthos Prime Handle', 'Nami Skyla Prime Blueprint', 'Braton Prime Blueprint'],
    ['Axi L3', 'Limbo Prime Chassis Blueprint', 'Zephyr Prime Chassis Blueprint', 'Akjagara Prime Receiver', 'Nami Skyla Prime Blueprint', 'Kronen Prime Blueprint', 'Fang Prime Handle'],
    ['Axi L4', 'Loki Prime Systems Blueprint', 'Volt Prime Systems Blueprint', 'Odonata Prime Blueprint', 'Wyrm Prime Carapace', 'Forma Blueprint', 'Bo Prime Ornament'],
    ['Axi L5', 'Limbo Prime Chassis Blueprint', 'Kronen Prime Handle', 'Akbronco Prime Link', 'Rubico Prime Stock', 'Fang Prime Blueprint', 'Burston Prime Blueprint'],
    ['Axi M1', 'Mirage Prime Blueprint', 'Rubico Prime Barrel', 'Orthos Prime Blueprint', 'Zhuge Prime String', 'Mesa Prime Chassis Blueprint', 'Lex Prime Barrel'],
    ['Axi M3', 'Mesa Prime Neuroptics Blueprint', 'Hydroid Prime Neuroptics Blueprint', 'Ballistica Prime Upper Limb', 'Fang Prime Blade', 'Akjagara Prime Blueprint', 'Forma Blueprint'],
    ['Axi N1', 'Ash Prime Systems Blueprint', 'Odonata Prime Wings Blueprint', 'Akstiletto Prime Link', 'Fang Prime Blade', 'Forma Blueprint', 'Braton Prime Blueprint'],
    ['Axi N2', 'Nikana Prime Hilt', 'Ash Prime Neuroptics Blueprint', 'Forma Blueprint', 'Bronco Prime Blueprint', 'Lex Prime Receiver', 'Carrier Prime Carapace'],
    ['Axi N3', 'Nekros Prime Blueprint', 'Bronco Prime Barrel', 'Volt Prime Blueprint', 'Forma Blueprint', 'Dual Kamas Prime Blueprint', 'Paris Prime Upper Limb'],
    ['Axi N4', 'Nikana Prime Hilt', 'Hydroid Prime Neuroptics Blueprint', 'Fragor Prime Handle', 'Nekros Prime Chassis Blueprint', 'Galatine Prime Blade', 'Cernos Prime Upper Limb'],
    ['Axi N5', 'Nami Skyla Prime Blade', 'Nekros Prime Neuroptics Blueprint', 'Helios Prime Systems', 'Oberon Prime Chassis Blueprint', 'Lex Prime Barrel', 'Euphona Prime Blueprint'],
    ['Axi N6', 'Nikana Prime Hilt', 'Saryn Prime Blueprint', 'Braton Prime Receiver', 'Braton Prime Barrel', 'Nikana Prime Blueprint', 'Lex Prime Receiver'],
    ['Axi N7', 'Nezha Prime Chassis Blueprint', 'Dethcube Prime Carapace', 'Forma Blueprint', 'Baza Prime Receiver', 'Astilla Prime Receiver', 'Octavia Prime Systems Blueprint'],
    ['Axi O1', 'Oberon Prime Systems Blueprint', 'Galatine Prime Handle', 'Akstiletto Prime Receiver', 'Forma Blueprint', 'Paris Prime Blueprint', 'Euphona Prime Blueprint'],
    ['Axi O2', 'Oberon Prime Systems Blueprint', 'Helios Prime Systems', 'Tiberon Prime Blueprint', 'Fang Prime Blade', 'Paris Prime String', 'Galatine Prime Blade'],
    ['Axi O3', 'Oberon Prime Systems Blueprint', 'Zephyr Prime Chassis Blueprint', 'Venka Prime Blueprint', 'Forma Blueprint', 'Destreza Prime Handle', 'Burston Prime Stock'],
    ['Axi O4', 'Oberon Prime Systems Blueprint', 'Gram Prime Blueprint', 'Tiberon Prime Blueprint', 'Destreza Prime Handle', 'Zephyr Prime Neuroptics Blueprint', 'Lex Prime Blueprint'],
    ['Axi P1', 'Pyrana Prime Blueprint', 'Ninkondi Prime Chain', 'Kogake Prime Blueprint', 'Forma Blueprint', 'Equinox Prime Chassis Blueprint', 'Akjagara Prime Blueprint'],
    ['Axi P2', 'Pyrana Prime Blueprint', 'Rubico Prime Stock', 'Destreza Prime Blueprint', 'Tiberon Prime Receiver', 'Dethcube Prime Systems', 'Bronco Prime Blueprint'],
    ['Axi P3', 'Pyrana Prime Blueprint', 'Wukong Prime Systems Blueprint', 'Burston Prime Barrel', 'Zhuge Prime Grip', 'Forma Blueprint', 'Bronco Prime Blueprint'],
    ['Axi R1', 'Rhino Prime Blueprint', 'Ankyros Prime Blade', 'Dakra Prime Blueprint', 'Boar Prime Receiver', 'Mag Prime Systems Blueprint', 'Boltor Prime Stock'],
    ['Axi R2', 'Redeemer Prime Handle', 'Mirage Prime Systems Blueprint', 'Chroma Prime Chassis Blueprint', 'Lex Prime Receiver', 'Forma Blueprint', 'Destreza Prime Handle'],
    ['Axi R3', 'Redeemer Prime Handle', 'Wukong Prime Systems Blueprint', 'Akjagara Prime Link', 'Zephyr Prime Neuroptics Blueprint', 'Stradavar Prime Stock', 'Fang Prime Blade'],
    ['Axi S1', 'Scindo Prime Blade', 'Trinity Prime Blueprint', 'Akbronco Prime Link', 'Bronco Prime Blueprint', 'Bronco Prime Receiver', 'Forma Blueprint'],
    ['Aki S2', 'Sicarus Prime Receiver', 'Forma Blueprint', 'Ember Prime Systems Blueprint', 'Wyrm Prime Blueprint', 'Loki Prime Blueprint', 'Latron Prime Receiver'],
    ['Axi S3', 'Scindo Prime Blade', 'Nyx Prime Systems Blueprint', 'Ankyros Prime Blade', 'Rhino Prime Systems Blueprint', 'Hikou Prime Stars', 'Boltor Prime Stock'],
    ['Axi S4', 'Soma Prime Stock', 'Nova Prime Blueprint', 'Dakra Prime Blade', 'Mag Prime Systems Blueprint', 'Forma Blueprint', 'Boar Prime Receiver'],
    ['Axi S5', 'Spira Prime Pouch', 'Nikana Prime Blade', 'Forma Blueprint', 'Venka Prime Blades', 'Saryn Prime Systems Blueprint', 'Cernos Prime Grip'],
    ['Axi S6', 'Sybaris Prime Barrel', 'Tigris Prime Barrel', 'Silva & Aegis Prime Blade', 'Nekros Prime Chassis Blueprint', 'Forma Blueprint', 'Burston Prime Blueprint'],
    ['Axi S7', 'Soma Prime Stock', 'Trinity Prime Chassis Blueprint', 'Kavasa Prime Kubrow Collar Blueprint', 'Vasto Prime Barrel', 'Nova Prime Systems Blueprint', 'Forma Blueprint'],
    ['Axi T1', 'Tigris Prime Blueprint', 'Burston Prime Barrel', 'Akstiletto Prime Receiver', 'Saryn Prime Systems Blueprint', 'Odonata Prime Harness Blueprint', 'Vectis Prime Barrel'],
    ['Axi T2', 'Tipedo Prime Handle', 'Forma Blueprint', 'Burston Prime Barrel', 'Stradavar Prime Stock', 'Mirage Prime Neuroptics Blueprint', 'Kogake Prime Boot'],
    ['Axi T3', 'Tipedo Prime Handle', 'Forma Blueprint', 'Equinox Prime Blueprint', 'Paris Prime Lower Limb', 'Limbo Prime Systems Blueprint', 'Burston Prime Blueprint'],
    ['Axi T4', 'Tipedo Prime Handle', 'Zhuge Prime Blueprint', 'Equinox Prime Blueprint', 'Wukong Prime Neuroptics Blueprint', 'Corinth Prime Blueprint', 'Braton Prime Blueprint'],
    ['Axi T5', 'Titania Prime Systems Blueprint', 'Gram Prime Blueprint', 'Forma Blueprint', 'Zhuge Prime String', 'Rubico Prime Receiver', 'Chroma Prime Blueprint'],
    ['Axi T6', 'Tekko Prime Blade', 'Wukong Prime Chassis Blueprint', 'Tenora Prime Stock', 'Zakti Prime Receiver', 'Paris Prime String', 'Forma Blueprint'],
    ['Axi T7', 'Tekko Prime Blade', 'Pangolin Prime Blade', 'Corinth Prime Receiver', 'Inaros Prime Systems Blueprint', 'Bronco Prime Receiver', 'Forma Blueprint'],
    ['Axi V1', 'Vauban Prime Chassis Blueprint', 'Forma Blueprint', 'Volt Prime Neuroptics Blueprint', 'Dual Kamas Prime Blueprint', 'Carrier Prime Systems', 'Odonata Prime Systems Blueprint'],
    ['Axi V2', 'Vectis Prime Stock', 'Boar Prime Barrel', 'Braton Prime Receiver', 'Mag Prime Neuroptics Blueprint', 'Trinity Prime Systems Blueprint', 'Hikou Prime Pouch'],
    ['Axi V3', 'Vectis Prime Stock', 'Braton Prime Receiver', 'Orthos Prime Blueprint', 'Trinity Prime Systems Blueprint', 'Vasto Prime Barrel', 'Trinity Prime Neuroptics Blueprint'],
    ['Axi V4', 'Vectis Prime Stock', 'Forma Blueprint', 'Cernos Prime Blueprint', 'Odonata Prime Harness Blueprint', 'Trinity Prime Systems Blueprint', 'Paris Prime Blueprint'],
    ['Axi V5', 'Valkyr Prime Chassis Blueprint', 'Tigris Prime Receiver', 'Braton Prime Receiver', 'Forma Blueprint', 'Dual Kamas Prime Blueprint', 'Venka Prime Blades'],
    ['Axi V6', 'Valkyr Prime Chassis Blueprint', 'Galatine Prime Handle', 'Fang Prime Handle', 'Forma Blueprint', 'Braton Prime Blueprint', 'Ballistica Prime Lower Limb'],
    ['Axi V7', 'Venka Prime Gauntlet', 'Silva & Aegis Prime Blueprint', 'Kogake Prime Blueprint', 'Valkyr Prime Blueprint', 'Nami Skyla Prime Blueprint', 'Lex Prime Barrel'],
    ['Axi V9', 'Venka Prime Gauntlet', 'Valkyr Prime Systems Blueprint', 'Spira Prime Blade', 'Valkyr Prime Blueprint', 'Saryn Prime Neuroptics Blueprint', 'Forma Blueprint'],
    ['Axi W1', 'Wukong Prime Blueprint', 'Inaros Prime Blueprint', 'Forma Blueprint', 'Stradavar Prime Receiver', 'Bronco Prime Receiver', 'Aksomati Prime Receiver'],
    ['Axi W2', 'Wukong Prime Blueprint', 'Inaros Prime Blueprint', 'Bronco Prime Barrel', 'Tekko Prime Gauntlet', 'Forma Blueprint', 'Baza Prime Receiver'],
    ['Axi Z1', 'Zakti Prime Blueprint', 'Zhuge Prime Blueprint', 'Baza Prime Barrel', 'Wukong Prime Neuroptics Blueprint', 'Panthera Prime Blueprint', 'Forma Blueprint'],
]

module.exports.data = data